name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Generate Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Rishi122005
          github_token: ${{ secrets.GITHUB_TOKEN }}
          games: pacman
          player_style: aggressive

      - name: Publish Pac-Man
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
